apiVersion: batch/v1
kind: Job
metadata:
  name: telemetrygen-metrics
  namespace: observability-lab
spec:
  template:
    spec:
      containers:
      - name: telemetrygen-metrics
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        args:
          - metrics
          - --otlp-endpoint=otel-collector.observability-lab.svc.cluster.local:4317
          - --otlp-insecure
          - --rate=10
          - --duration=30s
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: telemetrygen-logs
  namespace: observability-lab
spec:
  template:
    spec:
      containers:
      - name: telemetrygen-logs
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        args:
          - logs
          - --otlp-endpoint=otel-collector.observability-lab.svc.cluster.local:4317
          - --otlp-insecure
          - --rate=10
          - --duration=30s
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: telemetrygen-traces
  namespace: observability-lab
spec:
  template:
    spec:
      containers:
      - name: telemetrygen-traces
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        args:
          - traces
          - --otlp-endpoint=otel-collector.observability-lab.svc.cluster.local:4317
          - --otlp-insecure
          - --rate=10
          - --duration=30s
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
      restartPolicy: Never
  backoffLimit: 0
