# Spaceport demo application
# Sci-fi booking app with API, pricing-service and frontend

spaceport:
  enabled: true

  frontend:
    image:
      tag: "latest"

  api:
    image:
      tag: "latest"

  pricingService:
    image:
      tag: "latest"
