# Spaceport demo application
# Sci-fi booking app with API, pricing-service and frontend

spaceport:
  enabled: true
  api:
    image:
      tag: "v0.5.0"
  pricingService:
    image:
      tag: "v0.5.0"
  frontend:
    image:
      tag: "v0.5.0"