# Temporary values for testing NGDATA Mimir fork
# This will be used until upstream Grafana charts include monolithic mode

# Using NGDATA repository temporarily
global:
  clusterDomain: cluster.local

# Monolithic mode configuration
monolithic:
  enabled: true
  replicas: 1
  
  # Resource configuration
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi
  
  # Persistence
  persistence:
    enabled: true
    size: 10Gi
  
  # Configuration
  config:
    server:
      http_listen_port: 8080
      grpc_listen_port: 9095
      log_level: info
    
    common:
      storage:
        backend: s3
        s3:
          endpoint: minio:9000
          access_key_id: minio
          secret_access_key: minio123
          bucket_name: mimir-blocks
          insecure: true
    
    blocks_storage:
      backend: s3
      s3:
        endpoint: minio:9000
        access_key_id: minio
        secret_access_key: minio123
        bucket_name: mimir-blocks
        insecure: true
      tsdb:
        retention_period: 24h
    
    limits:
      ingestion_rate: 20000
      ingestion_burst_size: 200000

# Disable distributed components when using monolithic mode
distributor:
  enabled: false
ingester:
  enabled: false
querier:
  enabled: false
query_frontend:
  enabled: false
query_scheduler:
  enabled: false
ruler:
  enabled: false
compactor:
  enabled: false
store_gateway:
  enabled: false

# Service configuration
service:
  type: ClusterIP
  ports:
    http: 8080
    grpc: 9095

# Ingress configuration (if needed)
ingress:
  enabled: false

# ServiceMonitor for Prometheus scraping
serviceMonitor:
  enabled: true
  interval: 30s
