apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fiddeb/observabilitystack.git'
    targetRevision: auto   # Byt ut "develop" mot önskad branch
    path: helm/stacksharts
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true